vagrant_box/student_dashboard/config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :dojos

  get "dojos/:id/students/new", to: 'students#new',as: 'new_dojo_student'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

vagrant_box/student_dashboard/app/models/dojo.rb
class Dojo < ApplicationRecord
    has_many :students
end

vagrant_box/student_dashboard/app/models/student.rb
class Student < ApplicationRecord
  belongs_to :dojo
end

vagrant_box/student_dashboard/app/controllers/dojos_controller.rb
class DojosController < ApplicationController
  before_action :set_dojo, only: [:show, :edit, :update, :destroy]

  # GET /dojos
  # GET /dojos.json
  def index
    @dojos = Dojo.all
  end

  # GET /dojos/1
  # GET /dojos/1.json
  def show
    p @students
  end

  # GET /dojos/new
  def new
    @dojo = Dojo.new
  end

  # GET /dojos/1/edit
  def edit
  end

  # POST /dojos
  # POST /dojos.json
  def create
    @dojo = Dojo.new(dojo_params)

    respond_to do |format|
      if @dojo.save
        format.html { redirect_to @dojo, notice: 'Dojo was successfully created.' }
        format.json { render :show, status: :created, location: @dojo }
      else
        format.html { render :new }
        format.json { render json: @dojo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dojos/1
  # PATCH/PUT /dojos/1.json
  def update
    respond_to do |format|
      if @dojo.update(dojo_params)
        format.html { redirect_to @dojo, notice: 'Dojo was successfully updated.' }
        format.json { render :show, status: :ok, location: @dojo }
      else
        format.html { render :edit }
        format.json { render json: @dojo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dojos/1
  # DELETE /dojos/1.json
  def destroy
    @dojo.destroy
    respond_to do |format|
      format.html { redirect_to dojos_url, notice: 'Dojo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dojo
      @dojo = Dojo.find(params[:id])
      @students = @dojo.students.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dojo_params
      params.require(:dojo).permit(:branch, :street, :city, :state)
    end
end

vagrant_box/student_dashboard/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
    @dojos = Dojo.all
    @student.dojo = @dojos.find(params[:id])
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :email, :dojo_id)
    end
end

vagrant_box/student_dashboard/app/helpers/application_helper.rb
module ApplicationHelper
    
end

vagrant_box/student_dashboard/app/helpers/dojos_helper.rb
module DojosHelper
end

vagrant_box/student_dashboard/app/helpers/students_helper.rb
module StudentsHelper
end

vagrant_box/student_dashboard/app/views/dojos/_form.html.erb
<%= form_with(model: dojo, local: true) do |form| %>
  <% if dojo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dojo.errors.count, "error") %> prohibited this dojo from being saved:</h2>

      <ul>
      <% dojo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :branch %>
    <%= form.text_field :branch %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

vagrant_box/student_dashboard/app/views/dojos/edit.html.erb
<h1>Editing Dojo</h1>

<%= render 'form', dojo: @dojo %>

<%= link_to 'Show', @dojo %> |
<%= link_to 'Back', dojos_path %>

vagrant_box/student_dashboard/app/views/dojos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dojos</h1>

<table>
  <thead>
    <tr>
      <th>Branch</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dojos.each do |dojo| %>
      <tr>
        <td><%= dojo.branch %></td>
        <td><%= dojo.street %></td>
        <td><%= dojo.city %></td>
        <td><%= dojo.state %></td>
        <td><%= link_to 'Show', dojo %></td>
        <td><%= link_to 'Edit', edit_dojo_path(dojo) %></td>
        <td><%= link_to 'Destroy', dojo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dojo', new_dojo_path %>

vagrant_box/student_dashboard/app/views/dojos/new.html.erb
<h1>New Dojo</h1>

<%= render 'form', dojo: @dojo %>

<%= link_to 'Back', dojos_path %>

vagrant_box/student_dashboard/app/views/dojos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  
  <h1><%= @dojo.branch %></h1> <%= link_to 'Edit', edit_dojo_path(@dojo) %>
</p>

<p>
  <strong>Street:</strong>
  <%= @dojo.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @dojo.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @dojo.state %>
</p>
<h2>Student Roser </h2>
<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Dojo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.email %></td>
        <td><%= student.dojo.branch %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Home', dojos_path %> <%= link_to 'Add Student', new_dojo_student_path %> 