vagrant_box/lyster/config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
 
  resources :users
  resources :tournaments,shallow: true do
    resources :combatants
    resources :rounds do
      resources :matches do
        resources :points
      end
    end
  end
  

  



  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

vagrant_box/lyster/app/models/match.rb
class Match < ApplicationRecord
  belongs_to :round
  has_many :points, dependent: :destroy
end

vagrant_box/lyster/app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]
  before_action :set_round, only: [:show, :edit, :update, :destroy]
  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @points = @match.points.all
  end

  # GET /matches/new
  def new
    @round = Round.find(params[:round_id])
    @match = Match.new(round:@round)

  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to round_path(id:@match.round_id), action: 'show', notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to round_path(id:@match.round_id), action: 'show', notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to round_path(id:@match.round_id), action: 'show', notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end
    def set_round
      @round = @match.round
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:round_id)
    end
end

vagrant_box/lyster/app/helpers/matches_helper.rb
module MatchesHelper
end

vagrant_box/lyster/app/views/matches/_form.html.erb
<%= form_with(model: @match, url: (@match.new_record? ? round_matches_path(round_id:@round.id): match_path(id:@match.id)), local: true) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :round_id %>
    <%= form.text_field :round_id %>
  </div>

  <div class="actions">
  <%= form.submit ( form.object.new_record? ? "Create" : "Update"), class: 'btn btn-primary'%>
  </div>
<% end %>

vagrant_box/lyster/app/views/matches/_index.html.erb
<h1>Matches</h1>

<table>
  <thead>
    <tr>
      <th>Round</th>
      <th>Contender</th>
      <th>Challenger</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.round.number %></td>
        <% if match.points.count > 0 %>
        <td><%= match.points.first.contender.user.name %></td>
        <td><%= match.points.first.challenger.user.name %></td>
        <% else %>
          <td> define contender </td>
          <td> define challenger </td>
        <% end %>
        <td><%= link_to 'Show', match_path(id:match.id), class: 'btn btn-primary'  %></td>
        <td><%= link_to 'Edit', edit_match_path(id:match.id), class: 'btn btn-primary'  %></td>
        <td><%= link_to 'Destroy', match_path(id:match.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_round_match_path(round_id:@round.id), class: 'btn btn-primary'  %>

vagrant_box/lyster/app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', match_path(id:@match.id), class: 'btn btn-primary'  %> |
<%= link_to 'Back', round_path(id:@match.round.id), class: 'btn btn-primary'  %>

vagrant_box/lyster/app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Back',  round_path(id: params[:round_id]), class: 'btn btn-primary'  %>

vagrant_box/lyster/app/views/matches/show.html.erb
<div class='container'>
  <div class='row'>

    <div class='col-md-6'>
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Round:</strong>
        <%= @match.round.number %>
      </p>

      <%= link_to 'Edit', edit_match_path(id:@match.id), class: 'btn btn-primary'  %> |
      <%= link_to 'Back', round_path(id:@match.round.id), class: 'btn btn-primary'  %>
    </div>

      <div class='col-md-6'>
        <%= render :partial => 'points/index' %>
      </div>
  </div>
</div>