vagrant_box/lyster/config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
 
  resources :users
  resources :tournaments,shallow: true do
    resources :combatants
    resources :rounds do
      resources :matches do
        resources :points
      end
    end
  end
  

  



  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

vagrant_box/lyster/app/models/point.rb
class Point < ApplicationRecord
  belongs_to :match
  belongs_to :contender, class_name: "Combatant", foreign_key: "contender_id"
  belongs_to :challenger, class_name: "Combatant", foreign_key: "challenger_id"
end

vagrant_box/lyster/app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_point, only: [:show, :edit, :update, :destroy]
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /points
  # GET /points.json
  def index
    @points = Point.all
  end

  # GET /points/1
  # GET /points/1.json
  def show
  end

  # GET /points/new
  def new
    @match = Match.find(params[:match_id])
    @point = Point.new(match_id:@match.id)
    tourney = Tournament.find(@match.round.tournament.id)
    @combatants = tourney.combatants.all.collect{|u| [u.user.name, u.id]}
    
  end

  # GET /points/1/edit
  def edit
    tourney = @match.round.tournament
    @combatants = tourney.combatants.all.collect{|u| [u.user.name, u.id]}
  end

  # POST /points
  # POST /points.json
  def create
    @point = Point.new(point_params)
    @match = @point.match
    respond_to do |format|
      if @point.save
        format.html { redirect_to match_path(id:@match.id), action: 'show', notice: 'Point was successfully created.' }
        format.json { render :show, status: :created, location: @point }
      else
        
        format.html { render :new }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /points/1
  # PATCH/PUT /points/1.json
  def update
    respond_to do |format|
      if @point.update(point_params)
        format.html { redirect_to match_path(id:@match.id), action: 'show', notice: 'Point was successfully updated.' }
        format.json { render :show, status: :ok, location: @point }
      else
        format.html { render :edit }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    
    @point.destroy
    respond_to do |format|
      format.html { redirect_to match_path(id:@match.id), action: 'show', notice: 'Point was successfully updated.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point
      @point = Point.find(params[:id])
    end
    def set_match
      @match = @point.match
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def point_params
      params.require(:point).permit(:contender_id, :challenger_id, :contender_score, :challenger_score,:match_id)
    end
end

vagrant_box/lyster/app/helpers/points_helper.rb
module PointsHelper
end

vagrant_box/lyster/app/views/points/_form.html.erb
<%= form_with(model: @point, url: (@point.new_record? ? match_points_path(match_id:@match.id): point_path(id:@point.id)), local: true) do |form| %>
  <% if point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% point.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :contender_id %>
    <%= form.select :contender_id, @combatants %>
  </div>

  <div class="field">
    <%= form.label :challenger_id %>
    <%= form.select :challenger_id, @combatants %>
  </div>

  <div class="field">
    <%= form.label :contender_score %>
    <%= form.number_field :contender_score %>
  </div>

  <div class="field">
    <%= form.label :challenger_score %>
    <%= form.number_field :challenger_score %>
  </div>

  <div class="field">
    <%= form.label :match_id %>
    <%= form.text_field :match_id %>
  </div>

  <div class="actions">
  <%= form.submit ( form.object.new_record? ? "Create" : "Update"), class: 'btn btn-primary'%>  
  </div>
<% end %>

vagrant_box/lyster/app/views/points/_index.html.erb
<h1>Points</h1>

<table>
  <thead>
    <tr>
      <th>Contender</th>
      <th>Challenger</th>
      <th>Contender score</th>
      <th>Challenger score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @points.each do |point| %>
      <tr>
        <td><%= point.contender.user.name %></td>
        <td><%= point.challenger.user.name %></td>
        <td><%= point.contender_score %></td>
        <td><%= point.challenger_score %></td>
        <td><%= link_to 'Show', point_path(id:point.id) , class: 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_point_path(id:point.id) , class: 'btn btn-primary' %></td>
        <td><%= link_to 'Destroy', point_path(id:point.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Point', new_match_point_path(match_id:@match.id) , class: 'btn btn-primary' %>

vagrant_box/lyster/app/views/points/edit.html.erb
<h1>Editing Point</h1>

<%= render 'form', point: @point %>

<%= link_to 'Show', @point, class: 'btn btn-primary' %> |
<%= link_to 'Back', match_path, class: 'btn btn-primary' %>

vagrant_box/lyster/app/views/points/new.html.erb
<h1>New Point</h1>

<%= render 'form', point: @point, match: @match %>

<%= link_to 'Back', match_path(id:@match.id), class: 'btn btn-primary' %>

vagrant_box/lyster/app/views/points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contender:</strong>
  <%= @point.contender.user.name %>
</p>

<p>
  <strong>Challenger:</strong>
  <%= @point.challenger.user.name %>
</p>

<p>
  <strong>Contender score:</strong>
  <%= @point.contender_score %>
</p>

<p>
  <strong>Challenger score:</strong>
  <%= @point.challenger_score %>
</p>

<%= link_to 'Edit', edit_point_path(@point), class: 'btn btn-primary' %> |
<%= link_to 'Back', match_path, class: 'btn btn-primary' %>